guahao/Models/administrator.cs
namespace guahao.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("administrator")]
    public partial class administrator
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int id { get; set; }

        [StringLength(50)]
        public string name { get; set; }

        [StringLength(50)]
        public string password { get; set; }

        public int? hospital_id { get; set; }

        public short? permission { get; set; }
    }
}

guahao/Controllers/AdminAppointmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using guahao.Models;

namespace guahao.Controllers
{
    public class AdminAppointmentsController : Controller
    {
        private DB db = new DB();

        // GET: AdminAppointments
        public ActionResult Index()
        {
            string username = Session["admin"].ToString();
            var admin = db.administrator.Where(a => a.name == username).First().hospital_id;
            var per = db.administrator.Where(a => a.name == username).First().permission;
            if (per==1)
            {
                var res = (from hos in db.hospital.AsParallel()
                           where hos.id == admin
                           join dep in db.department.AsParallel() on hos.id equals dep.hospital_id
                           join doc in db.doctor.AsParallel() on dep.id equals doc.department_id
                           join app in db.appointment.AsParallel() on doc.id equals app.doctor_id
                           select app);
                return View(res.ToList().Take(50));
            }
            var appointment = db.appointment.Include(a => a.doctor).Include(a => a.hospital).Include(a => a.user);
            return View(appointment.ToList());
        }

        // GET: AdminAppointments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            appointment appointment = db.appointment.Find(id);
            if (appointment == null)
            {
                return HttpNotFound();
            }
            return View(appointment);
        }

        // GET: AdminAppointments/Create
        public ActionResult Create()
        {
            ViewBag.doctor_id = new SelectList(db.doctor, "id", "name");
            ViewBag.hospital_id = new SelectList(db.hospital, "id", "name");
            ViewBag.user_id = new SelectList(db.user, "id", "name");
            return View();
        }

        // POST: AdminAppointments/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,hospital_id,user_id,doctor_id,time,status,price")] appointment appointment)
        {
            if (ModelState.IsValid)
            {
                db.appointment.Add(appointment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.doctor_id = new SelectList(db.doctor, "id", "name", appointment.doctor_id);
            ViewBag.hospital_id = new SelectList(db.hospital, "id", "name", appointment.hospital_id);
            ViewBag.user_id = new SelectList(db.user, "id", "name", appointment.user_id);
            return View(appointment);
        }

        // GET: AdminAppointments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            appointment appointment = db.appointment.Find(id);
            if (appointment == null)
            {
                return HttpNotFound();
            }
            ViewBag.doctor_id = new SelectList(db.doctor, "id", "name", appointment.doctor_id);
            ViewBag.hospital_id = new SelectList(db.hospital, "id", "name", appointment.hospital_id);
            ViewBag.user_id = new SelectList(db.user, "id", "name", appointment.user_id);
            return View(appointment);
        }

        // POST: AdminAppointments/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,hospital_id,user_id,doctor_id,time,status,price")] appointment appointment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(appointment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.doctor_id = new SelectList(db.doctor, "id", "name", appointment.doctor_id);
            ViewBag.hospital_id = new SelectList(db.hospital, "id", "name", appointment.hospital_id);
            ViewBag.user_id = new SelectList(db.user, "id", "name", appointment.user_id);
            return View(appointment);
        }

        // GET: AdminAppointments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            appointment appointment = db.appointment.Find(id);
            if (appointment == null)
            {
                return HttpNotFound();
            }
            return View(appointment);
        }

        // POST: AdminAppointments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            appointment appointment = db.appointment.Find(id);
            db.appointment.Remove(appointment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

guahao/Controllers/AdminVisitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using guahao.Models;

namespace guahao.Controllers
{
    public class AdminVisitsController : Controller
    {
        private DB db = new DB();

        // GET: AdminVisits
        public ActionResult Index()
        {
            string username = Session["admin"].ToString();
            var admin = db.administrator.Where(a => a.name == username).First().hospital_id;
            var per = db.administrator.Where(a => a.name == username).First().permission;
            if(per==1)
            {
                var res = (from hos in db.hospital.AsParallel()
                           where hos.id == admin
                           join dep in db.department.AsParallel() on hos.id equals dep.hospital_id
                           join doc in db.doctor.AsParallel() on dep.id equals doc.department_id
                           join vis in db.visit.AsParallel() on doc.id equals vis.doctor_id
                           select vis);
                return View(res.ToList().Take(50));
            }
            return View(db.visit.ToList());

        }

        // GET: AdminVisits/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            visit visit = db.visit.Find(id);
            if (visit == null)
            {
                return HttpNotFound();
            }
            return View(visit);
        }

        // GET: AdminVisits/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminVisits/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,date,doctor_id,number,price")] visit visit)
        {
            if (ModelState.IsValid)
            {
                db.visit.Add(visit);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(visit);
        }

        // GET: AdminVisits/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            visit visit = db.visit.Find(id);
            if (visit == null)
            {
                return HttpNotFound();
            }
            return View(visit);
        }

        // POST: AdminVisits/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,date,doctor_id,number,price")] visit visit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(visit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(visit);
        }

        // GET: AdminVisits/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            visit visit = db.visit.Find(id);
            if (visit == null)
            {
                return HttpNotFound();
            }
            return View(visit);
        }

        // POST: AdminVisits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            visit visit = db.visit.Find(id);
            db.visit.Remove(visit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

guahao/Controllers/administratorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using guahao.Models;

namespace guahao.Controllers
{
    public class AdministratorsController : Controller
    {
        private DB db = new DB();

        // GET: administrators
        public ActionResult Index()
        {
            return View(db.administrator.ToList());
        }


        public ActionResult Login()
        {
            return View();
        }

     
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login([Bind(Include = "name,password")] administrator adm)
        {
            if (ModelState.IsValid)
            {
                var admin = db.administrator.FirstOrDefault(o => o.name == adm.name && o.password == adm.password);
                if (admin == null)
                {
                    ViewBag.NextUrl = "~/Administrators/Login";
                    ViewBag.Message = "登录失败：系统中无此管理员。";
                    return View("~/Views/Shared/Message.cshtml");
                }
                Session["admin"] = admin.name;
                return RedirectToAction("Details", "Administrators");
            }
            ViewBag.NextUrl = "~/Administrators/Login";
            ViewBag.Message = "登录失败：账号信息有误。";
            return View("~/Views/Shared/Message.cshtml");
        }

        public ActionResult Logout()
        {
            Session.Remove("admin");
            ViewBag.NextUrl = "~/Administrators/Login";
            ViewBag.Message = "您已成功登出。";
            return View("~/Views/Shared/Message.cshtml");
        }

        public ActionResult Details()
        {
            if (Session["admin"]==null)
                return RedirectToAction("Login","Administrators");
            string adminname = Session["admin"].ToString();
            var admin = db.administrator.FirstOrDefault(o => o.name == adminname);
            if (admin == null)
                return HttpNotFound();
            ViewBag.hospital = db.hospital.Where(h => h.id == admin.hospital_id).First().name;
            return View(admin);
        }

        public ActionResult UserList()
        {
            var userlist = db.user.Where(o => o.is_activated == null);
            return View(userlist.ToList());
        }

        // activate user if exits
        public ActionResult ActivateUser(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            user userinfo = db.user.Find(id);
            userinfo.is_activated = 1;
            db.SaveChanges();

            string admin= Session["admin"].ToString();
            int adminid = db.administrator.FirstOrDefault(o => o.name == admin).id;
            return RedirectToAction("UserList", "Administrators");
        }

        //judge if a user's apointment have over time. if so, decrease its credict
        public ActionResult BlackList()
        {
            DateTime today = DateTime.Now;
            foreach (user u in db.user)
            {
                var appo = db.appointment.Where(a => a.user_id == u.id);
                foreach (appointment app in appo)
                {
                    DateTime appday = (DateTime)app.time;
                    TimeSpan t = appday - today;
                    int days = t.Days;
                    if (days <= 0)
                        u.credict_rank -= 1;

                }
            }
            db.SaveChanges();
            return RedirectToAction("UserList", "Administrators");
        }
        
    }
}

guahao/Views/Administrators/Details.cshtml
@model guahao.Models.administrator

@{
    ViewBag.Title = "管理员信息";
    ViewBag.Location = "管理员 > 管理员信息";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewBag.Title</h1>

<div>
    <div class="row">
        <div class="col-md-9">
            <div class="row col-md-12">
                <div class="col-md-3 leftdiv">
                    @Html.LabelFor(model => model.name, "管理员账号")
                </div>
                <div class="col-md-8 rightdiv">
                    @Html.DisplayFor(model => model.name)
                </div>
            </div>
            @if (Model.permission.ToString() != "0")
            {
                <div class="row col-md-12">
                    <div class="col-md-3 leftdiv">
                        @Html.Label("所属医院")
                    </div>
                    <div class="col-md-8 rightdiv">
                        @ViewBag.hospital
                    </div>
                </div>
            }
        </div>
    </div>
</div>
<div class="btndiv">
    @if (Model.permission == 0)
    {
        @Html.ActionLink("审核注册信息", "UserList", "Administrators");
        @Html.ActionLink("管理出诊信息", "Index", "AdminVisits") ;
        @Html.ActionLink("管理预约信息", "Index", "AdminAppointments");
        @Html.ActionLink("违约惩罚", "BlackList", "Administrators") ;
    }
    else
    {
        //医院
        @Html.ActionLink("管理预约信息", "Index", "AdminAppointments");
        @Html.ActionLink("管理出诊信息", "Index", "AdminVisits") ;
    }
    @Html.ActionLink("退出登录", "Logout")
</div>

guahao/Views/Administrators/Login.cshtml
@model guahao.Models.administrator

@{
    ViewBag.Title = "管理员登录";
    ViewBag.Location = "首页 > 管理员登录";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewBag.Title</h1>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.name,"管理员名", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, "密码", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.password, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-primary btn-lg">登陆</button>
            </div>
        </div>
    </div>
}

guahao/Views/Administrators/UserList.cshtml
@model IEnumerable<guahao.Models.user>

@{
    ViewBag.Title = "审核注册信息";
    ViewBag.Location = Html.Raw(Html.ActionLink( "管理员","Details", "Administrators") + " > "
         + "审核注册信息");
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewBag.Title</h1>

<table class="table">
    <tr>
        <th>
            @Html.Label( "用户名")
        </th>
        <th>
            @Html.Label("真实姓名")
        </th>
        <th>
           @Html.Label("身份证号")
        </th>
        <th>
            @Html.Label("电话号码")
        </th>
        <th>
            @Html.Label("电子邮件")
        </th>
        <th>
           @Html.Label("是否激活")
        </th>
        <th>
            @Html.Label("信用等级")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.real_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.social_id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.is_activated)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.credict_rank)
        </td>
        <td>
            @Html.ActionLink("激活账户", "ActivateUser/"+@item.id, "Administrators") 
        </td>
    </tr>
}

</table>