guahao/Models/hospital.cs
namespace guahao.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("hospital")]
    public partial class hospital
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hospital()
        {
            appointment = new HashSet<appointment>();
            department = new HashSet<department>();
        }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int id { get; set; }

        [StringLength(100)]
        public string name { get; set; }

        [Column(TypeName = "ntext")]
        public string introduction { get; set; }

        public int? rank { get; set; }

        [Column(TypeName = "ntext")]
        public string address { get; set; }

        [StringLength(50)]
        public string tel { get; set; }

        [StringLength(50)]
        public string type { get; set; }

        [StringLength(10)]
        public string city { get; set; }

        [StringLength(80)]
        public string url { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<appointment> appointment { get; set; }

        public virtual city city1 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<department> department { get; set; }
    }
}

guahao/Controllers/HospitalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data;
using System.Web.Mvc;
using guahao.Models;
using System.Data.Entity;

namespace guahao.Controllers
{
    public class HospitalController : Controller
    {
        private DB db = new DB();
        // GET: Hospital
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SearchHospitalByName(string hname)
        {
            int number = 20;
            int page = 1;
            if (hname.Length <= 0)
            {
                var res = db.hospital.OrderBy(o => o.id).Skip((page - 1) * number).Take(number).ToList();
                Session.Remove("city");
                return View("~/Views/Hospital/HospitalList.cshtml", res);
            }
            else
            {
                var res = db.hospital.Where(o => o.name.IndexOf(hname) != -1).OrderBy(o => o.id).Skip((page - 1) * number).Take(number).ToList();
                Session["city"] = "\"" + hname + "\"";
                return View("~/Views/Hospital/HospitalList.cshtml", res);
            }
        }

        public ActionResult HospitalList(string cityname)
        {
            int number = 20;
            int page = 1;
            if (ModelState.IsValid)
            {
                var city = db.city.FirstOrDefault(o => o.name == cityname);
                if (city != null)
                {
                    string city_abv = db.city.FirstOrDefault(o => o.name == cityname).abr_name;
                    var hos = db.hospital.Where(o => o.city == city_abv).OrderBy(o => o.id).Skip((page - 1) * number).Take(number).ToList();
                    Session["city"] = cityname;
                    return View(hos);
                }
                else
                {
                    Session.Remove("city");
                    return View(db.hospital.OrderBy(o => o.id).Skip((page - 1) * number).Take(number).ToList());
                }
            }
            return View();
        }

        public ActionResult HospitalDetail(int? id)
        {
            Session["department"] = "";
            var hosDetail = db.hospital.Find(id);
            if (hosDetail == null)
            {
                return HttpNotFound();
            }
            Session["hospital"]=hosDetail.name;
            return View(hosDetail);
        }

        public ActionResult DepartmentList(int ?id)
        {
            int number = 20;
            int page = 1;
            Session["department"] = "";
            if (ModelState.IsValid)
            {
                //如果直接进入此页面，根据session找对应的医院
                if (id == null)
                {
                    if (Session["hospital"] != null)
                    {
                        var hosp = db.hospital.Where(h => h.name == Session["hospital"]).FirstOrDefault();
                        if (hosp == null)
                        {
                            return HttpNotFound();
                        }
                        else
                        {
                            id = hosp.id;
                        }
                    }
                    else
                    {
                        return HttpNotFound();
                    }
                }
                var dep = db.department.Where(o => o.hospital_id == id).OrderBy(o => o.id).Skip((page - 1) * number).Take(number).ToList();
                return View(dep);
            }else{
                return View();
            }
        }
        public ActionResult DoctorList(int ?id, string date)
        {
            int number = 20;
            int page = 1;
            if (ModelState.IsValid)
            {
                if (id == null) Session["department"] = "";
                else Session["department"] = db.department.Where(d => d.id == id).First().name;
                if (date != null && date.Length>0)
                {
                    DateTime dt = Convert.ToDateTime(date);
                    Session["appointment_date"] = date;
                    var doc = from d in db.doctor
                              where d.department_id == id
                              join v in db.visit on d.id equals v.doctor_id
                              where v.date == dt && v.number > 0
                              select d;
                    return View(doc.OrderBy(o => o.id).Skip((page - 1) * number).Take(number).ToList());
                }
                else
                {
                    Session["appointment_date"] = "";
                    var doc = db.doctor.Where(d => d.department_id == id).OrderBy(o => o.id).Skip((page - 1) * number).Take(number).ToList();
                    return View(doc);
                }

            }
            Session["department"] = "";
            return View();
        }
        

        public JsonResult LoadDoctor()
        {
             var doc = db.doctor.Where(o => o.department_id == 1);
            return Json(doc);
        }

        public ActionResult DoctorDetail(int? id)
        {
            if (id == null)
            {
                //根据Session原有记录打开相应的医生页面
                if(Session["hospital"]!=null && Session["department"]!=null && Session["doctor"]!=null)
                {
                    string hname = Session["hospital"].ToString();
                    string dname = Session["department"].ToString();
                    string docname = Session["doctor"].ToString();
                    var deps1 = db.hospital.Where(h => h.name == hname).FirstOrDefault();
                    if (deps1 != null)
                    {
                        var deps = deps1.department;
                        var docs = deps.Where(d => d.name == dname).First().doctor;
                        var docDetail1 = docs.Where(doc => doc.name == docname).First();
                        return View(docDetail1);
                    }
                }
            }
            var docDetail = db.doctor.Find(id);
            if (docDetail == null)
            {
                return HttpNotFound();
            }
            else
            {
                Session["doctor"] = docDetail.name;
                return View(docDetail);
            }
        }

        public ActionResult getVisitsByDate(int did,string date)
        {
            DateTime datetime = new DateTime(1999,1,1);
            try{
                 datetime=DateTime.Parse(date);
            }catch(Exception){}

            try {
                var sb=datetime.Date;
                DateTime nextDate = datetime.AddDays(1);
                var res = db.visit.Where(v => v.doctor_id == did && v.date >= datetime && v.date<nextDate).ToList();
                string result = "";
                foreach (var d in res)
                {
                    result += d.date.ToString() + ",";
                    result += d.number.ToString() + ",";
                    result += d.price.ToString() + ",";
                    result += d.doctor_id.ToString() + ",";
                }
                if (result.Length >= 1) result = result.Substring(0, result.Length - 1);
                return Content(result);
            }
            catch (Exception) { return View(); }

        }

    }
}

guahao/Views/Hospital/DepartmentList.cshtml
@model IEnumerable<guahao.Models.department>

@{
    ViewBag.Title = "科室列表";
    ViewBag.Location = Html.Raw(Html.ActionLink("首页", "Index", "Home") + " > "
        + Html.ActionLink("医院列表", "HospitalList", "Hospital") + " > "
    + "科室列表");
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@Session["hospital"] - @ViewBag.Title</h1>
<div class="show">
    @foreach (var department in Model)
    {
        <div class="g-hospital-items to-margin">
            <ul class="hos_ul">
                <li class="g-hospital-item J_hospitalItem">
                    <div class="hos-total g-clear " style="border: none;">
                        <div class="info g-left">
                            <dl>
                                <dt>
                                    @Html.ActionLink(@department.name, "DoctorList/" + @department.id, "Hospital")
                                </dt>
                            </dl>
                        </div>

                    </div>

                </li>
            </ul>
        </div>
    }
</div>

guahao/Views/Hospital/Detail.cshtml
@model guahao.Models.hospital

@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detail</h2>

<div>
    <h4>hospital</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.introduction)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.introduction)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rank)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rank)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.city)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.city)
        </dd>

    </dl>
</div>
<p>

    @Html.ActionLink("回到主页", "Index")
</p>

guahao/Views/Hospital/DoctorDetail.cshtml
@model guahao.Models.doctor

@{
    ViewBag.Title = "医生信息";
    ViewBag.Location = Html.Raw(Html.ActionLink("首页", "Index", "Home") + " > "
        + Html.ActionLink("医院列表", "HospitalList", "Hospital") + " > "
         + Html.ActionLink("科室列表", "DepartmentList", "Hospital") + " > "
    + "医生信息");
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@Session["hospital"] - @Session["department"] - @Session["doctor"] - @ViewBag.Title</h1>



<div class="row">
    <div class="col-md-3">
        @{
            int idnum = Model.id % 8 + 1;
            @Html.Raw("<img src='" + Url.Content("~/img/photos/doctor_") + idnum + ".jpg' width='100%' height='100%' />");
        }
    </div>
    <div class="col-md-9">
        <div class="row col-md-12">
            <div class="col-md-3 leftdiv">
                @Html.LabelFor(model => model.name, "医生姓名")
            </div>
            <div class="col-md-8 rightdiv">
                <label>@Html.DisplayFor(model => model.name)</label>
            </div>
        </div>
        <div class="row col-md-12">
            <div class="col-md-3 leftdiv">
                @Html.LabelFor(model => model.department.name, "所属科室")
            </div>
            <div class="col-md-8 rightdiv">
                <label>@Html.DisplayFor(model => model.department.name)</label>
            </div>
        </div>
        <div class="row col-md-12">
            <div class="col-md-3 leftdiv">
                @Html.LabelFor(model => model.rank, "级别")
            </div>
            <div class="col-md-8 rightdiv">
                <label>专家</label>
            </div>
        </div>
        <div class="row col-md-12">
            <div class="col-md-3 leftdiv">
                @Html.LabelFor(model => model.specialty, "专长")
            </div>
            <div class="col-md-8 rightdiv">
                <label>@Html.DisplayFor(model => model.specialty)</label>
            </div>
        </div>
        <div class="row col-md-12">
            <div class="col-md-3 leftdiv">
                @Html.LabelFor(model => model.is_good, "优秀医生")
            </div>
            <div class="col-md-8 rightdiv">
                <label>是</label>
            </div>
        </div>
    </div>
</div>

    <div class="row col-md-11">
        <label for="date"> 请选择要预约的日期</label>
        <div class="keyword">
            <input type="date" name="date" class="gray" id="date" value="" />
            <input type="hidden" id="doctorId" value="@Model.id" />
            <button type="submit" class="btn-doctor" onclick="searchByDate()">查询</button>
        </div>
    </div>

    <label for="date">可预约时段</label>
    <table class="table" id="dateSelectTable">
        <thead>
            <tr>
                <th>时间</th>
                <th>剩余人数</th>
                <th>价格</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>

<div class="row col-md-12">
    <div class="col-md-2 leftdiv">
        @Html.LabelFor(model => model.introduction, "医生介绍")
    </div>
    <div class="col-md-9 rightdiv">
        <label>@Html.DisplayFor(model => model.introduction)</label>
    </div>
</div>
<script>
    function searchByDate()
    {
        var did = $("#doctorId").val();
        var date=$("#date").val();
        $.ajax({
            url: "@Url.Action("getVisitsByDate","Hospital")",
            type: "POST",
            data: {
                'did': did,
                'date':date
            },
            success: function (datastr) {
                showDates(datastr);
            },
            error: function () {
                alert("查询出错");
            }
        });
    }

    //刷新table显示的日期
    function showDates(datastr)
    {
        var datetime=$("#date").val();
        var data=datastr.split(",");
        var table = $("#dateSelectTable tbody");
        var content = "";
        console.log(datastr);
        for (i = 0; i < data.length; i+=4)
        {
            content += "<tr>";
            content += "<td>" + data[i] + "</td>";
            content += "<td>" + data[i + 1] + "</td>";
            content += "<td>" + data[i + 2] + "</td>";
            datetime = data[i];
            content += "<td><a href='@Url.Content("~/Appointments/Create?did=")" + data[i + 3] + "&date=" + datetime + "' >预约</a></td>";
            content += "</tr>";
        }
        if (datastr.length <= 5) content = "<tr><td colspan='4'>无结果</td></tr>";
        table.html(content);
    }

</script>

guahao/Views/Hospital/DoctorList.cshtml
@model IEnumerable<guahao.Models.doctor>

@{
    ViewBag.Title = "医生列表";
    ViewBag.Location = Html.Raw(Html.ActionLink("首页", "Index", "Home") + " > "
        +Html.ActionLink("医院列表", "HospitalList", "Hospital") + " > "
         + Html.ActionLink("科室列表", "DepartmentList", "Hospital") + " > "
    + "医生列表");
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@Session["hospital"] - @Session["department"] - @ViewBag.Title</h1>
<div class="keyword">
    <label for="date"> 请选择要预约的日期</label>
    <form role="form" action="@Url.Action("DoctorList", "Hospital")" method="post">
        
        <input type="date" name="date" class="gray" id="date" value="" />
        <input type="hidden" name="id" value="@Model.FirstOrDefault().department_id" />
        <button type="submit" class="btn-doctor" id="querySearch">查询医生</button>
    </form>
</div>

<div class="show">
    @foreach (var doctor in Model)
    {
        <div class="g-hospital-items to-margin">
            <ul class="hos_ul">
                <li class="g-hospital-item J_hospitalItem">
                    <div class="hos-total g-clear " style="border: none;">
                        <div class="info g-left">
                            <div class="listimgdiv">
                                @{
                                    int idnum = doctor.id % 8 + 1;
                                    @Html.Raw("<img src='" + Url.Content("~/img/photos/doctor_") + idnum + ".jpg' width='100%' height='100%' />");
                                }
                            </div>
                            <dl>
                                <dt>
                                    @Html.ActionLink(@doctor.name, "DoctorDetail/" + @doctor.id, "Hospital")
                                </dt>
                                <dd>
                                    <p class="tel">
                                        <i></i>
                                        <span title="@doctor.specialty">@doctor.specialty</span>
                                    </p>
                                    <!-- 推荐内容科室或者医生 -->
                                </dd>
                            </dl>
                        </div>

                    </div>

                </li>
            </ul>
        </div>

    }
    @foreach (var doctor in Model)
    {
    }
</div>

guahao/Views/Hospital/HospitalDetail.cshtml
@model guahao.Models.hospital

@{
    ViewBag.Title = "医院信息";
    ViewBag.Location = Html.Raw(Html.ActionLink("首页", "Index", "Home") + " > "
        + Html.ActionLink("医院列表", "HospitalList", "Hospital") + " > "
+ "医院信息");
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@Session["hospital"] - @ViewBag.Title</h1>
<div>
    <div class="col-md-3">
        @{
            int idnum = Model.id % 8 + 1;
            @Html.Raw("<img src='" + Url.Content("~/img/photos/hospital_") + idnum + ".jpg' width='100%' height='100%' />");
        }
    </div>
    <div class="col-md-9">
        <div class="row col-md-12">
            <div class="col-md-3 leftdiv">
                @Html.LabelFor(model => model.name, "医院名称")
            </div>
            <div class="col-md-8 rightdiv">
                <label>@Html.DisplayFor(model => model.name)</label>
            </div>
        </div>
        <div class="row col-md-12">
            <div class="col-md-3 leftdiv">
                @Html.LabelFor(model => model.rank, "医院等级")
            </div>
            <div class="col-md-8 rightdiv">
                <label>三级甲等</label>
            </div>
        </div>
        <div class="row col-md-12">
            <div class="col-md-3 leftdiv">
                @Html.LabelFor(model => model.address, "医院地址")
            </div>
            <div class="col-md-8 rightdiv">
                <label>@Html.DisplayFor(model => model.address)</label>
            </div>
        </div>
        <div class="row col-md-12">
            <div class="col-md-3 leftdiv">
                @Html.LabelFor(model => model.tel, "医院电话")
            </div>
            <div class="col-md-8 rightdiv">
                <label>@Html.DisplayFor(model => model.tel)</label>
            </div>
        </div>
        <div class="row col-md-12">
            <div class="col-md-3 leftdiv">
                @Html.LabelFor(model => model.type, "医院类型")
            </div>
            <div class="col-md-8 rightdiv">
                <label>@Html.DisplayFor(model => model.type)</label>
            </div>
        </div>
        <div class="row col-md-12">
            <div class="col-md-3 leftdiv">
                @Html.LabelFor(model => model.city, "所属城市")
            </div>
            <div class="col-md-8 rightdiv">
                <label>
                @{
                    if(Model.city=="bj")
                    {
                        @Html.Raw("北京");
                    }
                    else if(Model.city=="sh")
                    {
                        @Html.Raw("上海");
                    }
                    else if(Model.city=="gz")
                    {
                        @Html.Raw("广州");
                    }
                    else
                    {
                         @Html.Raw(Model.city);
                    }
                }
                </label>
            </div>
        </div>
    </div>
</div>

<div class="row col-md-12">
    <div class="col-md-2 leftdiv">
        @Html.LabelFor(model => model.introduction, "医院介绍")
    </div>
    <div class="col-md-9 rightdiv">
        <label>@Html.DisplayFor(model => model.introduction)</label>
    </div>
</div>
<div class="row col-md-12 btndiv">
    <a href="javascript:history.go(-1);">返回</a>
    @Html.ActionLink("选择科室", "DepartmentList/"+@Model.id,"Hospital")
</div>

guahao/Views/Hospital/HospitalList.cshtml
@model IEnumerable<guahao.Models.hospital>
@{
    ViewBag.Title = "医院列表";
    ViewBag.Location = Html.Raw(Html.ActionLink("首页", "Index", "Home") + " > "
    + "医院列表");
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="show">
    @if (Session["city"] == null)
    {
            Session["city"] = "全部";
    }
    <h1>@Session["city"] -  @ViewBag.Title</h1>
    <div class="keyword">
        <form role="form" action="@Url.Action("SearchHospitalByName","Hospital")" method="post">
            <input type="search" name="hname" autocomplete="off" placeholder="请输入医院名,如：协和" class="gray" id="search" value="" />
            <button type="submit" class="btn-doctor" id="querySearch">搜&nbsp;索</button>
        </form>
    </div>
    @foreach (var hospital in Model)
    {
        <div class="g-hospital-items to-margin">
            <ul class="hos_ul">
                <li class="g-hospital-item J_hospitalItem">
                    <div class="hos-total g-clear " style="border: none;">
                        <div class="info g-left">
                            <div class="listimgdiv">
                                @{
                                        int idnum = hospital.id % 8 + 1;
                                       @Html.Raw("<img src='" + Url.Content("~/img/photos/hospital_") + idnum + ".jpg' width='100%' height='100%' />");
                                }
                            </div>
                            <dl>
                                <dt>
                                    @Html.ActionLink(@hospital.name, "HospitalDetail/" + @hospital.id, "Hospital")
                                    <em class="em2">三级甲等</em>
                                    <img src="@Url.Content("~/img/guahao.png")">
                                </dt>
                                <dd>
                                    <p class="tel">
                                        <i></i>
                                        <span title="@hospital.tel">@hospital.tel</span>
                                    </p>
                                    <p class="addr">
                                        <i></i>
                                        <span title="@hospital.address">@hospital.address</span>
                                    </p>
                                    <!-- 推荐内容科室或者医生 -->
                                </dd>
                            </dl>
                        </div>

                    </div>

                </li>
            </ul>
        </div>

    }

</div>