guahao/Models/appointment.cs
namespace guahao.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("appointment")]
    public partial class appointment
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int id { get; set; }

        public int? hospital_id { get; set; }

        public int? user_id { get; set; }

        public int? doctor_id { get; set; }

        public DateTime? time { get; set; }

        public byte? status { get; set; }

        public int? price { get; set; }

        public virtual doctor doctor { get; set; }

        public virtual hospital hospital { get; set; }

        public virtual user user { get; set; }
    }
}

guahao/Controllers/AppointmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using guahao.Models;

namespace guahao.Controllers
{
    public class AppointmentsController : Controller
    {
        private DB db = new DB();

        // GET: Appointments
        public ActionResult Index()
        {
            string uname = Session["user"].ToString();
            var appointment = db.appointment.Include(a => a.doctor).Include(a => a.hospital).Include(a => a.user).Where(a => a.user.name == uname);
            return View(appointment.ToList());
        }

        // GET: Appointments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            appointment appointment = db.appointment.Find(id);
            if (appointment == null)
            {
                return HttpNotFound();
            }
            return View(appointment);
        }
        public int IdGet()
        {
            int i = db.appointment.Count() + 1;
            if (i != 1)
                i = db.appointment.Max(o => o.id) + 1;
            return i;
        }

        // GET: Appointments/Create
        public ActionResult Create(int? did,string date)
        {
            if (did == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (Session["user"]==null)
            {
                ViewBag.NextUrl = "~/Account/Login";
                ViewBag.Message = "请先注册或登录。";
                return View("~/Views/Shared/Message.cshtml");
            }
            string uname = Session["user"].ToString();
            user user = db.user.FirstOrDefault(a => a.name == uname);
            // the case that user not login or not activated or has been black
            if (user==null||user.is_activated==null||user.credict_rank<=0)
            {
                ViewBag.NextUrl = "~/Account/UserInfo";
                ViewBag.Message = "您的账号还未实名认证，或者信用等级过低，无法进行预约操作。";
                return View("~/Views/Shared/Message.cshtml");
            }
           
            ViewBag.user_id = user.id;
            ViewBag.user_name = uname;
            ViewBag.doctor_id = did;
            doctor doctor = db.doctor.Find(did);
            ViewBag.doctor_name = doctor.name;
            ViewData["id"] = IdGet() ;
            if (date == null || date.Length <= 0)
            {
                if (Session["appointment_date"] != null)
                {
                    date = Session["appointment_date"].ToString();
                }
                else
                {
                    
                }
            }
            Session["appointment_date"] = date;
            DateTime dt = Convert.ToDateTime(date);
            ViewBag.time = dt;
            //the case that user had ordered more than 3 doctor at the same time
            int  app = db.appointment.Count(o => o.user_id == user.id&&o.time==dt);
            if (app>3)
            {
                ViewBag.Message = "同一时间段内不能预约超过三个医生，请稍后再试。";
                return View("~/Views/Shared/Message.cshtml");
            }
            //the case order the same doctor
            var appp = db.appointment.FirstOrDefault(o => o.user_id == user.id && o.time == dt && o.doctor_id == did);
            if (appp != null)
            {
                ViewBag.Message = "不能重复预约。";
                return View("~/Views/Shared/Message.cshtml");
            }
            //the case order the a doctor which in the same depatment
            //var apppp = db.appointment.Include(o => o.doctor.department_id == doctor.department_id).FirstOrDefault(o => o.user_id == user.id && o.time == dt);
            var apppp = from a in db.appointment
                        where a.user_id == user.id && a.time == dt
                        join d in db.doctor on a.doctor_id equals d.id
                        where d.department_id==doctor.department_id
                        select a;
            if (apppp.Count()>=1)
            {
                ViewBag.Message = "不能在同一时间段内预约同一科室的医生。";
                return View("~/Views/Shared/Message.cshtml");
            }
            var depart = db.department.FirstOrDefault(d=>d.id==doctor.department_id);
            var hospital = db.hospital.Find(depart.hospital_id);
            ViewBag.hospital_id = hospital.id;
            ViewBag.hospital_name = hospital.name;
            ViewBag.status = 0;
            ViewBag.price = db.visit.FirstOrDefault(o => o.date == dt && o.doctor_id == did).price;
            return View();
        }

    
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,hospital_id,user_id,doctor_id,time,status,price")] appointment appointment)
        {
            if (ModelState.IsValid)
            {
                db.appointment.Add(appointment);
                DateTime dt = Convert.ToDateTime(Session["appointment_date"].ToString());
                visit v = db.visit.FirstOrDefault(o => o.date == dt && o.doctor_id == appointment.doctor_id);
                v.number -= 1;
                db.SaveChanges();
                ViewBag.NextUrl = "~/Appointments/Index";
                ViewBag.Message = "预约单提交成功！请查看您的预约信息。";
                return View("~/Views/Shared/Message.cshtml");
            }

            ViewBag.doctor_id = new SelectList(db.doctor, "id", "name", appointment.doctor_id);
            ViewBag.hospital_id = new SelectList(db.hospital, "id", "name", appointment.hospital_id);
            ViewBag.user_id = new SelectList(db.user, "id", "name", appointment.user_id);
            ViewBag.Message = "预约失败。请查看您的预约信息是否正确。";
            return View("~/Views/Shared/Message.cshtml");
        }

       
        // GET: Appointments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            appointment appointment = db.appointment.Find(id);
            if (appointment == null)
            {
                return HttpNotFound();
            }
            DateTime today = DateTime.Now;
            DateTime appday = (DateTime)appointment.time;
            TimeSpan t = appday - today;
            int days = t.Days;
            //before the visit day
            if (days >= 1)
                return View(appointment);
            else
                return RedirectToAction("Index");
        }

        // POST: Appointments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            appointment app = db.appointment.Find(id);
            var v = db.visit.FirstOrDefault(o => o.date == app.time && o.doctor_id == app.doctor_id);
            v.number += 1;
            db.appointment.Remove(app);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Pay(int? aid)
        {
            Random r = new Random();
            int key1 = r.Next(0, 999999999);
            int key2 = r.Next(0, 999999999);
            ViewBag.payNumber = key1.ToString() + key2.ToString();
            ViewBag.id = aid;

            string uname = Session["user"].ToString();
            var userinfo = db.user.FirstOrDefault(o => o.name == uname);
            var app = db.appointment.Find(aid);
            doctor doc = db.doctor.Find(app.doctor_id);
            department dep = db.department.Find(doc.department_id);
            hospital hos = db.hospital.Find(dep.hospital_id);

            ViewBag.user_name = userinfo.real_name;
            ViewBag.doctor_name = doc.name;
            ViewBag.hospital_name = hos.name;
            ViewBag.time = app.time;
            ViewBag.price = app.price;
            return View();
        }

        [HttpPost]
        public ActionResult Pay2(int id)
        {
            string uname = Session["user"].ToString();
            var appoint = db.appointment.Where(a=>a.id==id).Include(a => a.doctor).Include(a => a.hospital).Include(a => a.user).Where(a => a.user.name == uname);
            foreach (appointment app in appoint)
            {
                app.status = 1;
            }
            db.SaveChanges();

            ViewBag.NextUrl = "~/Appointments/Index";
            ViewBag.Message = "支付成功！";
            return View("~/Views/Shared/Message.cshtml");
        }

        public ActionResult Print1(int ?id)
        {
            var app = db.appointment.Find(id);
            return View(app);
        }

        public ActionResult Print2(int? id)
        {
            var app = db.appointment.Find(id);
            return View(app);
        }
    }
}

guahao/Views/Appointments/Create.cshtml
@model guahao.Models.appointment

@{
    ViewBag.Title = "创建预约单";
    ViewBag.Location = Html.Raw(Html.ActionLink("首页", "Index", "Home") + " > "
        + "创建预约单");
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewBag.Title</h1>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.id, new{ @Value = @ViewBag.id ,@readonly="readonly"})
        @Html.HiddenFor(model => model.doctor_id, new { @Value = @ViewBag.doctor_id, @readonly = "readonly" })
        <div class="form-group">
            @Html.Label("医院名称", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.hospital_id, new{ @Value = @ViewBag.hospital_id, @readonly="readonly" })
                @ViewBag.hospital_name
            </div>
        </div>

        <div class="form-group">
            @Html.Label("预约人", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.user_id, new { @Value=@ViewBag.user_id ,@readonly="readonly"})
                @ViewBag.user_name
            </div>
        </div>
        <div class="form-group">
            @Html.Label("医生姓名", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               @ViewBag.doctor_name
            </div>        
        </div>
        <div class="form-group">
            @Html.Label("预约时间", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.time, new { @Value = @ViewBag.time, @readOnly = "readOnly" })
            </div>
        </div>
        @Html.HiddenFor(model => model.status, new { @Value = @ViewBag.status ,@readonly="readonly"})

        <div class="form-group">
            @Html.Label("价格", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.price, new { @Value = @ViewBag.price, @readOnly = "readOnly" })
            </div>
        </div>
        <div class="btndiv">
            <button type="submit" >确定</button>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

guahao/Views/Appointments/Delete.cshtml
@model guahao.Models.appointment

@{
    ViewBag.Title = "取消预约";
    ViewBag.Location = Html.Raw(Html.ActionLink("首页", "Index", "Home") + " > "
        + "取消预约");
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewBag.Title</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>appointment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.LabelFor(model => model.doctor.name,"预约医生")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.doctor.name)
        </dd>

        <dt>
            @Html.LabelFor(model => model.hospital.name,"预约医院")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hospital.name)
        </dd>

        <dt>
            @Html.LabelFor(model => model.user.name,"预约用户")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.user.name)
        </dd>

        <dt>
            @Html.LabelFor(model => model.time,"预约时间")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.time)
        </dd>


        <dt>
            @Html.LabelFor(model => model.price,"应缴费用")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.price)
        </dd>

        <dt>
            @Html.LabelFor(model => model.status, "缴费状态")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>


    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("回到主页", "Index")
        </div>
    }
</div>

guahao/Views/Appointments/Details.cshtml
@model guahao.Models.appointment

@{
    ViewBag.Title = "预约信息";
    ViewBag.Location = Html.Raw(Html.ActionLink("首页", "Index", "Home") + " > "
        + Html.ActionLink("查看预约单", "Index", "Appointments") + " > "
        + "预约信息");
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewBag.Title</h1>

<div>
    <div class="row">
        <div class="col-md-9">
            <div class="row col-md-12">
                <div class="col-md-3 leftdiv">
                    @Html.LabelFor(model => model.doctor.name, "预约医生")
                </div>
                <div class="col-md-8 rightdiv">
                    @Html.DisplayFor(model => model.doctor.name)
                </div>
            </div>
            <div class="row col-md-12">
                <div class="col-md-3 leftdiv">
                    @Html.LabelFor(model => model.hospital.name, "预约医院")
                </div>
                <div class="col-md-8 rightdiv">
                    @Html.DisplayFor(model => model.hospital.name)
                </div>
            </div>
            <div class="row col-md-12">
                <div class="col-md-3 leftdiv">
                    @Html.LabelFor(model => model.user.name, "预约用户")
                </div>
                <div class="col-md-8 rightdiv">
                    @Html.DisplayFor(model => model.user.name)
                </div>
            </div>
            <div class="row col-md-12">
                <div class="col-md-3 leftdiv">
                    @Html.LabelFor(model => model.time, "预约时间")
                </div>
                <div class="col-md-8 rightdiv">
                    @Html.DisplayFor(model => model.time)
                </div>
            </div>
            <div class="row col-md-12">
                <div class="col-md-3 leftdiv">
                    @Html.LabelFor(model => model.price, "应缴费用")
                </div>
                <div class="col-md-8 rightdiv">
                    @Html.DisplayFor(model => model.price)
                </div>
            </div>
            <div class="row col-md-12">
                <div class="col-md-3 leftdiv">
                    @Html.LabelFor(model => model.status, "缴费状态")
                </div>
                <div class="col-md-8 rightdiv">
                    @if (Model.status == 0)
                    {
                        @Html.Label("未缴费")
                    }
                    else
                    {
                        @Html.Label("已缴费")
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<div class="btndiv">
    <a href="javascript:history.go(-1);">返回</a>
</div>

guahao/Views/Appointments/Index.cshtml
@model IEnumerable<guahao.Models.appointment>

@{
    ViewBag.Title = "查看预约单";
    ViewBag.Location = Html.Raw(Html.ActionLink("首页", "Index", "Home") + " > "
        + "查看预约单");
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewBag.Title</h1>
<div class="row col-md-10">
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.Label("医生名称")
                </th>
                <th>
                    @Html.Label("医院名称")
                </th>
                <th>
                    @Html.Label("预约用户")
                </th>
                <th>
                    @Html.Label("预约时间")
                </th>
                <th>
                    @Html.Label("缴费状态")
                </th>
                <th>
                    @Html.Label("预约价格")
                </th>
                <th>
                    @Html.Label("操作")
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.doctor.name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.hospital.name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.user.name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.time)
                    </td>
                    <td>
                        @if (item.status == 0)
                        {
                            @Html.Label("未缴费")
                        }
                        else
                        {
                            @Html.Label("已缴费")
                        }

                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.price)
                    </td>
                    <td>
                        @Html.ActionLink("打印预约单", "Print1/" + @item.id, "Appointments")|
                        @if (@item.status == 0)
                        {
                            @Html.ActionLink("支付费用", "Pay", "Appointments", new { aid = @item.id }, null)
                        }
                        else
                        {
                            @Html.ActionLink("打印挂号单", "Print2/" + @item.id, "Appointments")

                        }
                        @Html.ActionLink("明细查看", "Details", new { id = item.id }) |
                        @Html.ActionLink("删除", "Delete", new { id = item.id })
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

guahao/Views/Appointments/Pay.cshtml
@model guahao.Models.appointment

@{
    ViewBag.Title = "支付";
    ViewBag.Location = Html.Raw(Html.ActionLink("首页", "Index", "Home") + " > "
        + Html.ActionLink("查看预约单", "Index", "Appointments") + " > "
        + "支付");
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewBag.Title</h1>

@using (Html.BeginForm("Pay2","Appointments"))
{
    @Html.AntiForgeryToken()


    <div>
        <label style="margin:20px;font-size:14px;">订单信息</label>
        <div class="row">
            <div class="col-md-9">
                <div class="row col-md-12">
                    <div class="col-md-3 leftdiv">
                        @Html.Label("医院名称")
                    </div>
                    <div class="col-md-8 rightdiv">
                        @ViewBag.hospital_name
                    </div>
                </div>
                <div class="row col-md-12">
                    <div class="col-md-3 leftdiv">
                        @Html.Label("预约人")
                    </div>
                    <div class="col-md-8 rightdiv">
                        @ViewBag.user_name
                    </div>
                </div>
                <div class="row col-md-12">
                    <div class="col-md-3 leftdiv">
                        @Html.Label("医生姓名")
                    </div>
                    <div class="col-md-8 rightdiv">
                        @ViewBag.doctor_name
                    </div>
                </div>
                <div class="row col-md-12">
                    <div class="col-md-3 leftdiv">
                        @Html.Label("预约时间")
                    </div>
                    <div class="col-md-8 rightdiv">
                        @Html.TextBoxFor(model => model.time, new { @Value = @ViewBag.time, @readOnly = "readOnly" })
                    </div>
                </div>
                <div class="row col-md-12">
                    <div class="col-md-3 leftdiv">
                        @Html.Label("价格")
                    </div>
                    <div class="col-md-8 rightdiv">
                        @Html.TextBoxFor(model => model.price, new { @Value = @ViewBag.price, @readOnly = "readOnly" })
                    </div>
                </div>
                @Html.HiddenFor(model => model.id, new { @Value = @ViewBag.id, @readonly = "readonly" })
                <div class="row col-md-12">
                    <div class="col-md-3 leftdiv">
                        @Html.Label("支付单号")
                    </div>
                    <div class="col-md-8 rightdiv">
                        @ViewBag.payNumber
                    </div>
                </div>
                <div class="row col-md-12">
                    <div class="col-md-3 leftdiv">
                        @Html.Label("支付密码")
                    </div>
                    <div class="col-md-8 rightdiv">
                        @Html.Password("password2", null, new { @class = "form-control" })
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="btndiv">
        <button type="submit">确认支付 </button>
    </div>
}
 

guahao/Views/Appointments/Print1.cshtml
@model guahao.Models.appointment

@{
    ViewBag.Title = "打印预约单";
    ViewBag.Location = Html.Raw(Html.ActionLink("首页", "Index", "Home") + " > "
        + Html.ActionLink("查看预约单", "Index", "Appointments") + " > "
        + "打印预约单");
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewBag.Title</h1>

<div class="row">
    <div class="col-md-1">
    </div>
    <div class="col-md-9">
        <div class="row col-md-12">
            <div class="col-md-3 leftdiv">
                @Html.Label("医生")
            </div>
            <div class="col-md-8 rightdiv">
                @Html.DisplayFor(model => model.doctor.name)
            </div>
        </div>
        <div class="row col-md-12">
            <div class="col-md-3 leftdiv">
                @Html.Label("医院")
            </div>
            <div class="col-md-8 rightdiv">
                @Html.DisplayFor(model => model.hospital.name)
            </div>
        </div>
        <div class="row col-md-12">
            <div class="col-md-3 leftdiv">
                @Html.Label("预约人")
            </div>
            <div class="col-md-8 rightdiv">
                @Html.DisplayFor(model => model.user.real_name)
            </div>
        </div>
        <div class="row col-md-12">
            <div class="col-md-3 leftdiv">
                @Html.Label("预约时间")
            </div>
            <div class="col-md-8 rightdiv">
                @Html.DisplayFor(model => model.time)
            </div>
        </div>
        <div class="row col-md-12">
            <div class="col-md-3 leftdiv">
                @Html.Label("应缴费用")
            </div>
            <div class="col-md-8 rightdiv">
                @Html.DisplayFor(model => model.price)
            </div>
        </div>
        <div class="row col-md-12">
            <div class="col-md-3 leftdiv">
                @Html.Label("状态")
            </div>
            <div class="col-md-8 rightdiv">
                @if (Model.status == 0)
                {
                    @Html.Label("未缴费")
                }
                else
                {
                    @Html.Label("已缴费")
                }
            </div>
        </div>
    </div>
</div>
<div class="btndiv">
    <a href="javascript:history.go(-1);">返回</a>
    <a href="javascript:StartPrint()">打印</a>
</div>

<script>
    function StartPrint() {
        alert("开始打印");
        window.print();
    }
</script>

guahao/Views/Appointments/Print2.cshtml
@model guahao.Models.appointment

@{
    ViewBag.Title = "打印挂号单";
    ViewBag.Location = Html.Raw(Html.ActionLink("首页", "Index", "Home") + " > "
        + Html.ActionLink("查看预约单", "Index", "Appointments") + " > "
        + "打印挂号单");
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewBag.Title</h1>

<div class="row">
    <div class="col-md-1">
    </div>
    <div class="col-md-9">
        <div class="row col-md-12">
            <div class="col-md-3 leftdiv">
                @Html.Label("医生")
            </div>
            <div class="col-md-8 rightdiv">
                @Html.DisplayFor(model => model.doctor.name)
            </div>
        </div>
        <div class="row col-md-12">
            <div class="col-md-3 leftdiv">
                @Html.Label("医院")
            </div>
            <div class="col-md-8 rightdiv">
                @Html.DisplayFor(model => model.hospital.name)
            </div>
        </div>
        <div class="row col-md-12">
            <div class="col-md-3 leftdiv">
                @Html.Label("预约人")
            </div>
            <div class="col-md-8 rightdiv">
                @Html.DisplayFor(model => model.user.real_name)
            </div>
        </div>
        <div class="row col-md-12">
            <div class="col-md-3 leftdiv">
                @Html.Label("预约时间")
            </div>
            <div class="col-md-8 rightdiv">
                @Html.DisplayFor(model => model.time)
            </div>
        </div>
        <div class="row col-md-12">
            <div class="col-md-3 leftdiv">
                @Html.Label("应缴费用")
            </div>
            <div class="col-md-8 rightdiv">
                @Html.DisplayFor(model => model.price)
            </div>
        </div>
        <div class="row col-md-12">
            <div class="col-md-3 leftdiv">
                @Html.Label("状态")
            </div>
            <div class="col-md-8 rightdiv">
                @Html.Label("已缴费")
            </div>
        </div>
    </div>
</div>
<div class="btndiv">
    <a href="javascript:history.go(-1);">返回</a>
    <a href="javascript:StartPrint()">打印</a>
</div>

<script>
    function StartPrint() {
        alert("开始打印");
        window.print();
    }
</script>